name: ci
on:
  push:
    tags:
      - v*
  pull_request:

jobs:
  tests:
    name: Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          check-latest: true
          cache: true
      - name: Run Tests
        run: |
          make test

  lint:
    name: Lint Code
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          check-latest: true
          cache: true
      - name: Run Linter
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 5m

  release:
    name: Release
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - tests
      - lint
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          check-latest: true
      - name: Install Ko
        uses: imjasonh/setup-ko@v0.6
      - name: Release a New Version
        run: make ci_release
        env:
          RELEASE_TAG: ${{github.ref_name}}
          GH_TOKEN: ${{ github.token }}
